steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/positive-rhino-454912-k2/fyuse-image', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/positive-rhino-454912-k2/fyuse-image']

  # Step 3: Deploy the service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fyuse-gc-image'
      - '--image=gcr.io/positive-rhino-454912-k2/fyuse-image'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-all'
      - '--update-env-vars=BUCKET_NAME=fyuse-static-assets' # Non-sensitive variable
      - '--update-env-vars=NEXT_PUBLIC_UPLOAD_API_URL=${_NEXT_PUBLIC_UPLOAD_API_URL}'
      - '--update-env-vars=NEXT_PUBLIC_FITANALYSIS_API_URL=${_NEXT_PUBLIC_FITANALYSIS_API_URL}'
      - '--update-env-vars=NEXT_PUBLIC_TRYON_TRACK=${_NEXT_PUBLIC_TRYON_TRACK}'
      - '--update-env-vars=NEXT_PUBLIC_HISTORY_HANDLER=${_NEXT_PUBLIC_HISTORY_HANDLER}'
      - '--update-env-vars=NEXT_PUBLIC_REMOVE_ITEM=${_NEXT_PUBLIC_REMOVE_ITEM}'
      - '--update-env-vars=NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}'
      - '--update-env-vars=NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=${_NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}'
      - '--update-env-vars=NEXTAUTH_URL=${_NEXTAUTH_URL}'
      - '--update-env-vars=NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'

# Specify the images to be built
images: ['gcr.io/positive-rhino-454912-k2/fyuse-image']

# Configure logging options
options:
  logging: CLOUD_LOGGING_ONLY

# Define substitution variables for secrets
availableSecrets:
  secretManager:
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXT_PUBLIC_UPLOAD_API_URL/versions/latest
      env: '_NEXT_PUBLIC_UPLOAD_API_URL'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXT_PUBLIC_FITANALYSIS_API_URL/versions/latest
      env: '_NEXT_PUBLIC_FITANALYSIS_API_URL'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXT_PUBLIC_TRYON_TRACK/versions/latest
      env: '_NEXT_PUBLIC_TRYON_TRACK'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXT_PUBLIC_HISTORY_HANDLER/versions/latest
      env: '_NEXT_PUBLIC_HISTORY_HANDLER'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXT_PUBLIC_REMOVE_ITEM/versions/latest
      env: '_NEXT_PUBLIC_REMOVE_ITEM'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXT_PUBLIC_GOOGLE_CLIENT_ID/versions/latest
      env: '_NEXT_PUBLIC_GOOGLE_CLIENT_ID'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXT_PUBLIC_GOOGLE_CLIENT_SECRET/versions/latest
      env: '_NEXT_PUBLIC_GOOGLE_CLIENT_SECRET'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXTAUTH_URL/versions/latest
      env: '_NEXTAUTH_URL'
    - versionName: projects/positive-rhino-454912-k2/secrets/NEXTAUTH_SECRET/versions/latest
      env: '_NEXTAUTH_SECRET'