steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/positive-rhino-454912-k2/fyuse-image', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/positive-rhino-454912-k2/fyuse-image']

  # Step 3: Deploy the service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fyuse-gc-image'
      - '--image=gcr.io/positive-rhino-454912-k2/fyuse-image'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-env-vars=BUCKET_NAME=fyuse-static-assets'
      - '--update-env-vars=NEXT_PUBLIC_UPLOAD_API_URL=https://asia-southeast2-positive-rhino-454912-k2.cloudfunctions.net/uploadImage'
      - '--update-env-vars=NEXT_PUBLIC_FITANALYSIS_API_URL=https://asia-southeast2-positive-rhino-454912-k2.cloudfunctions.net/matchingAnalyzer'
      - '--update-env-vars=NEXT_PUBLIC_GOOGLE_CLIENT_ID=671019984810-u8r9lk9efcv16q2dje7vdgp70ul5aqgd.apps.googleusercontent.com'
      - '--update-env-vars=NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=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'
      - '--update-env-vars=NEXT_PUBLIC_TRYON_TRACK=https://asia-southeast2-positive-rhino-454912-k2.cloudfunctions.net/tryonTracking'
      - '--update-env-vars=NEXT_PUBLIC_HISTORY_HANDLER=https://asia-southeast2-positive-rhino-454912-k2.cloudfunctions.net/historyhandler'
      - '--update-env-vars=NEXT_PUBLIC_REMOVE_ITEM=https://asia-southeast2-positive-rhino-454912-k2.cloudfunctions.net/removeFromWardrobe'
      - '--update-env-vars=NEXTAUTH_URL=https://fyuse-gc-image-671019984810.asia-southeast1.run.app'
      - '--update-env-vars=NEXTAUTH_SECRET=6Aw2LfF2C08fOiDm8cw5iI6jO9Ln1qfWEXHR4XLVNnc='
      - '--set-env-vars=CORS_ALLOWED_ORIGINS=https://fyuse-gc-image-671019984810.asia-southeast1.run.app'

# Specify the images to be built
images: ['gcr.io/positive-rhino-454912-k2/fyuse-image']

# Configure logging options
options:
  logging: CLOUD_LOGGING_ONLY